Treasurer in progress
kkbagrryantsev/nsu-mountain-network-frontend pull request #18
Opened 2023-05-21 14:51 UTC by Mikhail05Evdokimov

2023-05-21 17:21 UTC, kkbagrryantsev requested changes
Всё здорово, надо всякие штуки подправить. Возможно сделать пользователей как ряды с разделителями как в Вк

2023-05-21 17:21 UTC, kkbagrryantsev commented on src/pages/profile-page/content/treasurer-options/TreasurerPageTab.js
> +  const users = useSelector((state) => state.treasurerPage.users);
Зачем? В этой функции они не используются

2023-05-21 17:21 UTC, kkbagrryantsev commented on src/pages/profile-page/content/treasurer-options/TreasurerPageTab.js
> +  const usersL = useSelector((state) => state.treasurerPage.users.loading);
Навзание надо написать понятно

2023-05-21 17:21 UTC, kkbagrryantsev commented on src/pages/profile-page/content/treasurer-options/TreasurerPageSaga.js
> +      yield put(setAllUsers({ data: [], status: LoadingState.ERROR }));
Надо как-то уведомить пользователя что не загрузилось либо здесь через createErrorToast, либо на странице через элемент загрузчика

2023-05-21 17:21 UTC, kkbagrryantsev commented on src/pages/profile-page/content/treasurer-options/styles/TreasurerPage.module.scss
> +  .itemCard {
Для адаптивного размера под разные дисплеи есть breakpoints https://mdbootstrap.com/docs/react/layout/columns/ , их можно указать в className у объекта, тогда этот файл вообще не понадобится

2023-05-21 17:21 UTC, kkbagrryantsev commented on src/pages/profile-page/content/treasurer-options/styles/TreasurerPage.module.scss
> +.userTable {
Тоже можно в className указать

2023-05-21 17:21 UTC, kkbagrryantsev commented on src/pages/profile-page/content/treasurer-options/content/UserCard.js
> +  const onClickAddToCart = (i) => {
Сигма

2023-05-21 17:21 UTC, kkbagrryantsev commented on src/pages/profile-page/content/sections/Sections.js
> +          image={treasurer}
Картинку заменить на любую красивую с dddepth

2023-05-21 17:21 UTC, kkbagrryantsev commented on src/pages/profile-page/content/sections/Sections.js
> +    <MDBRow style={{marginTop: "2%"}}>
Лучше отступы задавать сразу для всех в родительском div, a margin обычно вообще зло. Margin, padding, gutter, gap проще задавать в className https://mdbootstrap.com/docs/react/utilities/spacing/

2023-05-21 17:21 UTC, kkbagrryantsev commented on src/pages/profile-page/content/treasurer-options/content/UserCard.js
> +        <MDBCol size={"100"} className={"ps-0"}>
size указывается от 1 до 12. В ряду может максимум 12 колонок. У Col размер задается в этих колонках

2023-05-21 17:21 UTC, kkbagrryantsev commented on src/pages/profile-page/content/treasurer-options/content/UserCard.js
> +        className={`bage`}
className не нужен

2023-05-23 08:00 UTC, Mikhail05Evdokimov commented on src/pages/profile-page/content/treasurer-options/TreasurerPageTab.js
> +  const users = useSelector((state) => state.treasurerPage.users);
Для дебага надо было

2023-05-23 18:06 UTC, Mikhail05Evdokimov commented
Ошибку 404 присылает с бэкэнда

2023-05-23 19:29 UTC, kkbagrryantsev requested changes

2023-05-23 19:29 UTC, kkbagrryantsev commented on src/pages/profile-page/content/treasurer-options/TreasurerPageSlice.js
> +      state.users = new StateWithLoader(action.payload, LoadingState.LOADED);
Надо либо setAll делать, либо set по id пользователя или как он там называется. Но лучше не изменять по ID данные, а просто обновлять в компоненте JS данные, а новые с бэка придут при перезагрузке страницы

2023-05-23 19:29 UTC, kkbagrryantsev commented on src/pages/profile-page/content/treasurer-options/TreasurerPageTab.js
>          <MDBCol md={"20"}>
md размер задает в колонках, их максимум 12 штук в ряду

2023-05-23 19:29 UTC, kkbagrryantsev commented on src/pages/profile-page/content/treasurer-options/content/UserCard.js
> +        className={`bage`}
В Badge className не нужен

2023-05-23 19:29 UTC, kkbagrryantsev commented on src/pages/profile-page/content/treasurer-options/content/ChangeBalanceDialog.js
> +                setIsActive();
Лучше явно указывать что false

2023-05-23 19:29 UTC, kkbagrryantsev commented on src/pages/profile-page/content/treasurer-options/content/ChangeBalanceDialog.js
> +                dispatch(modifyUserBalanceAction(auser));
У тебя отправляет значение, которое лежит в auser, а оно задается из formValue, если formValue изменится, то не факт, что auser при этом изменится. Надо напрямую formValue передавать

2023-05-29 06:55 UTC, Mikhail05Evdokimov commented
Looks like it is ready

2023-05-29 15:31 UTC, kkbagrryantsev requested changes
Подправь и смержим

2023-05-29 15:31 UTC, kkbagrryantsev commented on src/pages/profile-page/content/treasurer-options/TreasurerPageSaga.js
> +      money: parseInt(action.payload.formValue.newBalance, 10),
Такие штуки надо передавать сразу нужными объектами. У тебя поменяется много раз ещё код в компоненте, а эти вызовы должны работать всегда

2023-05-29 15:31 UTC, kkbagrryantsev commented on src/pages/profile-page/content/treasurer-options/TreasurerPageSaga.js
> +      money: parseInt(action.payload.formValue.newBalance, 10),
Плюс если парсинг делать в компоненте, то здесь вообще этот блок кода исчезнет

2023-05-29 15:31 UTC, kkbagrryantsev commented on src/pages/profile-page/content/sections/Sections.js
> +          md={"50%"}
Договорились же не делать их сеткой одинакового размера

2023-05-29 15:31 UTC, kkbagrryantsev commented on src/api/models/ApiCalls.js
> +  axios.patch(`/api/models/users/${data.user.user_login}`, data, getAccessTokenHeader());
Здесь тоже лучше 2 параметра передать сразу нужного формата, чтобы при изменении кода не рефакторить все уровни от компоненты до саги и api вызова

2023-05-29 15:31 UTC, kkbagrryantsev commented on src/pages/profile-page/ProfilePage.js
> +              <Sections roles = {user.user_roles}/>
Есть вызов на роли пользователя, его лучше вызвать из Sections, а не передавать туда. Меньше мороки потом будет с зависимостями

2023-05-29 15:31 UTC, kkbagrryantsev commented on src/pages/profile-page/content/sections/Sections.js
> +function RolesParser(roles, role) {
С большой буквы только компоненты и классы именуются

2023-05-29 17:11 UTC, kkbagrryantsev approved these changes

2023-05-29 17:16 UTC, kkbagrryantsev approved these changes

2023-05-29 17:17 UTC, kkbagrryantsev approved these changes

2023-05-29 17:17 UTC, merged